name: Deploy Fake
on:
    workflow_call:
        inputs:
            ambiente:
                type: string
                default: "desenvolvimento"
                required: true
                description: "Ambiente onde vai ser feito o deploy"
jobs:
    deploy_kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando deploy no ambiente de ${{ inputs.ambiente }}"