name: Deploy Fake
on:
    workflow_call:
        secrets:
            ambiente:
                required: true
                description: "Ambiente onde vai ser feito o deploy"
jobs:
    deploy_kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando deploy no ambiente de ${{ secrets.ambiente }}"
